name:                haskell-playground
version:             0.1.0.0
bitbucket:           "zoltan_p/haskell-playground"
license:             BSD3
author:              "Zoltan Pal"
copyright:           "2019 Zoltan Pal"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-playground:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-playground

tests:
  haskell-playground-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-playground
